### ISSUE TITLE
Error when phenology fitting is enabled

### ISSUE THREAD

**Issue by valpasq** [ceholden/yatsm#49]
Error occurs when attempting to run phenology fitting:
```
  File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/cli/line.py", line 190, in line
    ltm = pheno.LongTermMeanPhenology(yatsm, **cfg['phenology'])
TypeError: __init__() got an unexpected keyword argument 'year_interval'
```

Config location: /projectnb/landsat/projects/Massachusetts/p012r031/p012r031_config.yaml

**Comment by ceholden** [comment]
Whoops. If you look at [line 190 of `yatsm line`](https://github.com/ceholden/yatsm/blob/master/yatsm/cli/line.py#L190) you'll see that I'm passing the entire `phenology` section of the config file to the `__init__` method of the LTM phenology class. Some of the configuration options are actually for the `fit` method, and one of them (`enable`) is just a toggle.

This speaks to a larger issue when parameterizing the algorithms with a config file -- we probably need to separate the `__init__` and `fit` sections. An example of what I'm proposing would be as follows:

``` yaml
# Section for phenology fitting
phenology:
    enable: False
    init:
	    # Specification for dataset indices required for EVI based phenology monitoring
	    red_index: 2
	    nir_index: 3
	    blue_index: 0
	    # Scale factor for reflectance bands
	    scale: 0.0001
	    # You can also specify index of EVI if contained in dataset to override calculation
	    evi_index:
	    evi_scale:
    fit:
        # Number of years to group together when normalizing EVI to upper and lower percentiles
        year_interval: 3
        # Upper and lower percentiles of EVI used for max/min scaling
        q_min: 10
        q_max: 90
```

This way it's clear what are hyperparameters and what are parameters used in the fitting. Related to #50
