### ISSUE TITLE
Config file subsections -- init and fit

### ISSUE THREAD

**Issue by ceholden** [ceholden/yatsm#52]
To make our configuration files better pair with the [scikit-learn estimator API](http://scikit-learn.org/stable/developers/#apis-of-scikit-learn-objects), each timeseries model must now be configured using an `init` and `fit` subsection. 

Example from some made up estimator:

``` yaml
MadeUpModel:
    init:
        threshold: 3
        likelihood: binomial
        sided: two-sided
    fit:
        sample_weights: '1 / vza'
```

This greatly improves the flexibility of the configuration files because it explicitly declared what configuration settings are for what methods. This can be extended for other methods (e.g., `transform`) for scikit-learn-like APIs.
